import type { GetStaticProps, NextPage } from 'next'
import { File, AboutData, JobData, ProjectData } from '@/types/index';
import { jobsData, aboutData, projectsData } from '@/lib/files'; 

import Head from 'next/head'
import styles from '../styles/Home.module.css'

type HomeProps = {
  about: File<AboutData>,
  jobs: File<JobData>[],
  projects: File<ProjectData>[],
}

const Home: NextPage<HomeProps> = ({ about, jobs, projects }) => {
  console.log(about, jobs, projects)
  return (
    <div className={styles.container}>
      <Head>
        <title>Tatiana Inama - Javascript developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        <p>hello</p>
      </header>
      <main className={styles.main}>
      </main>

      <footer className={styles.footer}>
      </footer>
    </div>
  )
}

export const getStaticProps: GetStaticProps<HomeProps> = async () => {
  return {
    props: {
      about: aboutData,
      jobs: jobsData,
      projects: projectsData,
    }
  }
}

export default Home
