import type { GetStaticProps, NextPage } from 'next'
import { File, AboutData, JobData, ProjectData } from '@/types/index'
import { jobsData, aboutData, projectsData } from '@/lib/files'

import Head from 'next/head'
import Card from '@/components/Card'
import styles from '../styles/Home.module.css'

type HomeProps = {
  about: File<AboutData>
  jobs: File<JobData>[]
  projects: File<ProjectData>[]
}

const Home: NextPage<HomeProps> = ({ about, jobs, projects }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>
          {about.data.name} - {about.data.title}
        </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className={styles.header}>
        <Card>
          <h1>
            {about.data.name} <small>{about.data.title}</small>
          </h1>
          <div dangerouslySetInnerHTML={{ __html: about.content }} />
        </Card>
      </header>
      <main className={styles.main}>
        {jobs.map(({ id, data, content }) => (
          <Card key={id}>
            <h2>{data.company}</h2>
            <div dangerouslySetInnerHTML={{ __html: content }} />
          </Card>
        ))}
        {projects.map(({ id, data, content }) => (
          <Card key={id}>
            <h3>{data.project}</h3>
            <div dangerouslySetInnerHTML={{ __html: content }}></div>
          </Card>
        ))}
      </main>

      <footer className={styles.footer}>
        <Card>
          <h5>footer</h5>
        </Card>
      </footer>
    </div>
  )
}

export const getStaticProps: GetStaticProps<HomeProps> = async () => {
  return {
    props: {
      about: aboutData,
      jobs: jobsData,
      projects: projectsData,
    },
  }
}

export default Home
